CREATE DATABASE ABHISHEK_PRACTICE;
USE ABHISHEK_PRACTICE;
CREATE TABLE EMPLOYEE(ID INT NOT NULL PRIMARY KEY, NAME VARCHAR(30), OCCUPATION VARCHAR(30));
INSERT INTO EMPLOYEE VALUES(1, "ABHI", "SE");
INSERT INTO EMPLOYEE VALUES(2, "RAINA", "SSE");
INSERT INTO EMPLOYEE VALUES(3, "ABHISHEK", "SW ARCHITECT");
INSERT INTO EMPLOYEE VALUES(4, "ABHI", "TL");
INSERT INTO EMPLOYEE VALUES(5, "ABHIS", "TL");